repos:
-   repo: local
    hooks:
    - id: black
      name: black
      language: system
      description: 'Format code'
      entry: black
      types: [python]
      args:
        - --line-length=79
