repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
      description: 'Format code'
      entry: black
      types: [python]
      args:
        - --line-length=79
        
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      name: flake8
      description: 'Check logic issues'
      language: system
      entry: flake8
      types: [python]

