repos:
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    - id: black
      language_version: python3.6
      description: 'Format code'
      entry: black
      types: [python]
      args:
        - --line-length=79   
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    - id: flake8
      name: flake8
      description: 'Check logic issues'
      language_version: python3.6
      entry: flake8
      types: [python]

